export const SET_QUESTIONS = "SET_QUESTIONS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const GET_QUESTION = "GET_QUESTION";
export const UPDATE_SINGLE_QUESTION = "UPDATE_SINGLE_QUESTION";
